"""
HOPE Safety Disclaimers

Legal and safety messaging for mental health application.
All text is available in multiple languages for global deployment.

CRITICAL: These messages are legally important. Changes require
review by legal and clinical advisors.
"""

from typing import Dict, List
from dataclasses import dataclass


@dataclass
class SafetyDisclaimer:
    """A safety disclaimer with multi-language support."""
    
    key: str
    languages: Dict[str, str]
    
    def get(self, language: str = "en") -> str:
        """Get disclaimer in requested language, fallback to English."""
        return self.languages.get(language[:2].lower(), self.languages["en"])


# =============================================================================
# NON-MEDICAL DISCLAIMER (Required for all users)
# =============================================================================

NON_MEDICAL_DISCLAIMER = SafetyDisclaimer(
    key="non_medical",
    languages={
        "en": """
IMPORTANT: HOPE is an AI-powered support tool, NOT a medical service.

• HOPE is not a substitute for professional mental health care
• HOPE cannot diagnose, treat, or cure any mental health condition
• HOPE's responses are generated by AI and may not always be accurate
• In a medical emergency, call emergency services (911 in US, 999 in UK, 112 in EU)

By using HOPE, you acknowledge that you understand these limitations.
""".strip(),
        
        "fr": """
IMPORTANT : HOPE est un outil de soutien basé sur l'IA, PAS un service médical.

• HOPE ne remplace pas les soins professionnels de santé mentale
• HOPE ne peut pas diagnostiquer, traiter ou guérir de troubles mentaux
• Les réponses de HOPE sont générées par IA et peuvent ne pas être précises
• En cas d'urgence médicale, appelez le 15 (SAMU) ou le 112

En utilisant HOPE, vous reconnaissez comprendre ces limitations.
""".strip(),
        
        "ar": """
هام: HOPE هو أداة دعم تعمل بالذكاء الاصطناعي، وليس خدمة طبية.

• HOPE ليس بديلاً عن الرعاية النفسية المتخصصة
• HOPE لا يمكنه تشخيص أو علاج أي حالة نفسية
• ردود HOPE يتم إنشاؤها بواسطة الذكاء الاصطناعي وقد لا تكون دقيقة دائماً
• في حالات الطوارئ الطبية، اتصل بخدمات الطوارئ

باستخدامك HOPE، فإنك تقر بأنك تفهم هذه القيود.
""".strip(),
        
        "de": """
WICHTIG: HOPE ist ein KI-gestütztes Unterstützungstool, KEIN medizinischer Dienst.

• HOPE ist kein Ersatz für professionelle psychische Gesundheitsversorgung
• HOPE kann keine psychischen Erkrankungen diagnostizieren oder behandeln
• Die Antworten von HOPE werden von KI generiert und sind möglicherweise nicht immer genau
• Im medizinischen Notfall rufen Sie 112 an

Durch die Nutzung von HOPE erkennen Sie an, dass Sie diese Einschränkungen verstehen.
""".strip(),
        
        "es": """
IMPORTANTE: HOPE es una herramienta de apoyo con IA, NO un servicio médico.

• HOPE no sustituye la atención profesional de salud mental
• HOPE no puede diagnosticar, tratar o curar ninguna condición mental
• Las respuestas de HOPE son generadas por IA y pueden no ser precisas
• En una emergencia médica, llame al 112 o servicios de emergencia

Al usar HOPE, reconoce que comprende estas limitaciones.
""".strip(),
    }
)


# =============================================================================
# CRISIS ESCALATION MESSAGES
# =============================================================================

CRISIS_HEADER = SafetyDisclaimer(
    key="crisis_header",
    languages={
        "en": "It sounds like you may be in crisis. Please reach out for immediate support:",
        "fr": "Il semble que vous soyez en crise. Veuillez demander une aide immédiate :",
        "ar": "يبدو أنك قد تكون في أزمة. يرجى طلب الدعم الفوري:",
        "de": "Es scheint, dass Sie sich in einer Krise befinden. Bitte suchen Sie sofortige Unterstützung:",
        "es": "Parece que podrías estar en crisis. Por favor busca apoyo inmediato:",
    }
)

CRISIS_REASSURANCE = SafetyDisclaimer(
    key="crisis_reassurance",
    languages={
        "en": "You are not alone. Help is available 24/7.",
        "fr": "Vous n'êtes pas seul(e). De l'aide est disponible 24h/24.",
        "ar": "لست وحدك. المساعدة متاحة على مدار الساعة.",
        "de": "Sie sind nicht allein. Hilfe ist rund um die Uhr verfügbar.",
        "es": "No estás solo/a. Hay ayuda disponible las 24 horas.",
    }
)

HUMAN_ESCALATION = SafetyDisclaimer(
    key="human_escalation",
    languages={
        "en": "I'm an AI and my ability to help in a crisis is limited. Please speak to a real person who can provide proper support.",
        "fr": "Je suis une IA et ma capacité à aider en situation de crise est limitée. Veuillez parler à une vraie personne qui peut vous apporter un soutien approprié.",
        "ar": "أنا ذكاء اصطناعي وقدرتي على المساعدة في الأزمات محدودة. يرجى التحدث إلى شخص حقيقي يمكنه تقديم الدعم المناسب.",
        "de": "Ich bin eine KI und meine Fähigkeit, in einer Krise zu helfen, ist begrenzt. Bitte sprechen Sie mit einem echten Menschen, der angemessene Unterstützung bieten kann.",
        "es": "Soy una IA y mi capacidad para ayudar en una crisis es limitada. Por favor, habla con una persona real que pueda brindarte el apoyo adecuado.",
    }
)


# =============================================================================
# CRISIS HOTLINES BY REGION
# =============================================================================

@dataclass
class CrisisHotline:
    """Crisis hotline information."""
    
    country_code: str
    country_name: str
    hotline_name: str
    phone_number: str
    languages: List[str]
    hours: str  # e.g., "24/7" or "9am-5pm"


CRISIS_HOTLINES: Dict[str, CrisisHotline] = {
    "US": CrisisHotline(
        country_code="US",
        country_name="United States",
        hotline_name="988 Suicide & Crisis Lifeline",
        phone_number="988",
        languages=["en", "es"],
        hours="24/7",
    ),
    "UK": CrisisHotline(
        country_code="UK",
        country_name="United Kingdom",
        hotline_name="Samaritans",
        phone_number="116 123",
        languages=["en"],
        hours="24/7",
    ),
    "FR": CrisisHotline(
        country_code="FR",
        country_name="France",
        hotline_name="Numéro National de Prévention du Suicide",
        phone_number="3114",
        languages=["fr"],
        hours="24/7",
    ),
    "DE": CrisisHotline(
        country_code="DE",
        country_name="Germany",
        hotline_name="Telefonseelsorge",
        phone_number="0800 111 0 111",
        languages=["de"],
        hours="24/7",
    ),
    "ES": CrisisHotline(
        country_code="ES",
        country_name="Spain",
        hotline_name="Teléfono de la Esperanza",
        phone_number="024",
        languages=["es"],
        hours="24/7",
    ),
    "AU": CrisisHotline(
        country_code="AU",
        country_name="Australia",
        hotline_name="Lifeline",
        phone_number="13 11 14",
        languages=["en"],
        hours="24/7",
    ),
    "CA": CrisisHotline(
        country_code="CA",
        country_name="Canada",
        hotline_name="Crisis Services Canada",
        phone_number="988",
        languages=["en", "fr"],
        hours="24/7",
    ),
    "INT": CrisisHotline(
        country_code="INT",
        country_name="International",
        hotline_name="International Association for Suicide Prevention",
        phone_number="https://www.iasp.info/resources/Crisis_Centres/",
        languages=["en"],
        hours="Varies by region",
    ),
}


def get_crisis_hotline(country_code: str = "US") -> CrisisHotline:
    """Get crisis hotline for country, fallback to US."""
    return CRISIS_HOTLINES.get(country_code.upper(), CRISIS_HOTLINES["US"])


def format_crisis_message(
    language: str = "en",
    country_code: str = "US",
) -> str:
    """
    Format complete crisis message with hotline.
    
    Returns ready-to-display crisis support message.
    """
    hotline = get_crisis_hotline(country_code)
    
    message = f"""
{CRISIS_HEADER.get(language)}

📞 {hotline.hotline_name}: {hotline.phone_number}

{CRISIS_REASSURANCE.get(language)}

{HUMAN_ESCALATION.get(language)}
""".strip()
    
    return message


# =============================================================================
# BETA PROGRAM TERMS
# =============================================================================

BETA_TERMS = SafetyDisclaimer(
    key="beta_terms",
    languages={
        "en": """
HOPE BETA PROGRAM

You are participating in a controlled beta test of HOPE.

By continuing, you agree that:
1. HOPE is experimental software and may contain errors
2. Your feedback helps improve the service
3. You will report any concerning AI responses
4. You understand this is NOT a medical service
5. You will seek professional help if needed

Your safety is our priority. The panic support features are designed
to provide immediate relief, but are not a replacement for
professional mental health care.
""".strip(),
        
        "fr": """
PROGRAMME BÊTA HOPE

Vous participez à un test bêta contrôlé de HOPE.

En continuant, vous acceptez que :
1. HOPE est un logiciel expérimental et peut contenir des erreurs
2. Vos commentaires aident à améliorer le service
3. Vous signalerez toute réponse IA préoccupante
4. Vous comprenez que ceci N'EST PAS un service médical
5. Vous chercherez une aide professionnelle si nécessaire

Votre sécurité est notre priorité.
""".strip(),
    }
)


# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================

def get_all_disclaimers(language: str = "en") -> Dict[str, str]:
    """Get all disclaimers in specified language."""
    return {
        "non_medical": NON_MEDICAL_DISCLAIMER.get(language),
        "crisis_header": CRISIS_HEADER.get(language),
        "crisis_reassurance": CRISIS_REASSURANCE.get(language),
        "human_escalation": HUMAN_ESCALATION.get(language),
        "beta_terms": BETA_TERMS.get(language),
    }


def audit_crisis_messaging() -> Dict[str, any]:
    """
    Audit all crisis messaging for completeness.
    
    Returns report of missing or incomplete messaging.
    """
    required_languages = ["en", "fr", "es", "de", "ar"]
    
    issues = []
    
    # Check disclaimers
    disclaimers = [
        NON_MEDICAL_DISCLAIMER,
        CRISIS_HEADER,
        CRISIS_REASSURANCE,
        HUMAN_ESCALATION,
    ]
    
    for disclaimer in disclaimers:
        for lang in required_languages:
            if lang not in disclaimer.languages:
                issues.append({
                    "type": "missing_translation",
                    "key": disclaimer.key,
                    "language": lang,
                })
    
    # Check hotlines
    required_countries = ["US", "UK", "FR", "DE", "ES"]
    for country in required_countries:
        if country not in CRISIS_HOTLINES:
            issues.append({
                "type": "missing_hotline",
                "country": country,
            })
    
    return {
        "complete": len(issues) == 0,
        "issues": issues,
        "languages_supported": required_languages,
        "countries_covered": list(CRISIS_HOTLINES.keys()),
        "disclaimers_count": len(disclaimers),
    }
