/// Legal Documents Content
/// 
/// Real privacy policy and terms of service content.
/// Versioned and timestamped for compliance.

class LegalDocument {
  final String version;
  final DateTime lastUpdated;
  final String title;
  final String content;
  final List<String> applicableJurisdictions;
  
  const LegalDocument({
    required this.version,
    required this.lastUpdated,
    required this.title,
    required this.content,
    required this.applicableJurisdictions,
  });
}

/// Legal Documents Provider
/// 
/// Provides real legal documents with versioning.
class LegalDocuments {
  static const String privacyPolicyVersion = '1.0.0';
  static const String termsVersion = '1.0.0';
  
  static final LegalDocument privacyPolicy = LegalDocument(
    version: privacyPolicyVersion,
    lastUpdated: DateTime(2026, 1, 5),
    title: 'Privacy Policy',
    applicableJurisdictions: ['EU', 'US', 'UK', 'FR', 'DE', 'ES'],
    content: '''
HOPE Privacy Policy
Version $privacyPolicyVersion | Last Updated: January 5, 2026

1. INTRODUCTION

HOPE ("we", "our", "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our mobile application.

2. INFORMATION WE COLLECT

2.1 Information You Provide
• Chat messages during support sessions
• Panic episode data (severity, duration, interventions used)
• Settings preferences
• Optional: Email address if you create an account

2.2 Automatically Collected Information
• Device type and operating system
• App usage statistics (anonymized)
• Crash reports (anonymized)
• Session timestamps

2.3 Voice Data (if enabled)
• Voice transcripts are processed in real-time
• Audio recordings are NOT stored
• Transcripts are stored with your session data

3. HOW WE USE YOUR INFORMATION

We use your information to:
• Provide personalized panic support
• Improve our AI responses
• Analyze app performance
• Comply with legal obligations

We do NOT:
• Sell your data to third parties
• Use your data for advertising
• Share identifiable data with researchers without consent

4. DATA STORAGE AND SECURITY

• Data is encrypted in transit (TLS 1.3) and at rest (AES-256)
• Data is stored on secure servers within the EU
• We retain session data for 1 year, then automatically delete
• You can delete your data at any time via Settings

5. YOUR RIGHTS (GDPR/CCPA)

You have the right to:
• Access your data (Settings → Export Data)
• Delete your data (Settings → Clear History)
• Withdraw consent at any time
• Request data portability
• Lodge a complaint with a supervisory authority

6. CHILDREN'S PRIVACY

HOPE is intended for users aged 13 and older. We do not knowingly collect data from children under 13.

7. AI AND AUTOMATED DECISIONS

• HOPE uses AI (Google Gemini) to generate supportive responses
• AI does not make medical diagnoses
• AI responses are safety-filtered before display
• You always have the option to contact human crisis resources

8. CHANGES TO THIS POLICY

We may update this policy. You will be notified of significant changes and asked to re-consent.

9. CONTACT US

For privacy inquiries: privacy@hope-app.com
Data Protection Officer: dpo@hope-app.com

---

By using HOPE, you acknowledge that you have read and understood this Privacy Policy.
''',
  );
  
  static final LegalDocument termsOfService = LegalDocument(
    version: termsVersion,
    lastUpdated: DateTime(2026, 1, 5),
    title: 'Terms of Service',
    applicableJurisdictions: ['Global'],
    content: '''
HOPE Terms of Service
Version $termsVersion | Last Updated: January 5, 2026

1. ACCEPTANCE OF TERMS

By downloading, installing, or using HOPE, you agree to be bound by these Terms of Service.

2. DESCRIPTION OF SERVICE

HOPE is an AI-powered panic intervention support application that provides:
• Real-time conversational support during panic episodes
• Breathing and grounding exercises
• Crisis resource information
• Session history and progress tracking

3. NOT A SUBSTITUTE FOR PROFESSIONAL CARE

IMPORTANT: HOPE is NOT a replacement for professional mental health care, therapy, or emergency services.

• HOPE provides AI-generated supportive responses only
• HOPE does NOT provide medical diagnoses or treatment
• HOPE does NOT replace human counselors or therapists
• In a medical emergency, call your local emergency services

4. USER RESPONSIBILITIES

You agree to:
• Use HOPE only for its intended purpose
• Not misuse or attempt to exploit the service
• Provide accurate information
• Not use HOPE if you are under 13 years old

5. AI-GENERATED CONTENT

• All responses are generated by AI (Google Gemini)
• Responses are filtered for safety but may not always be perfect
• You should use your own judgment when following any suggestions
• We are not liable for AI-generated content accuracy

6. PRIVACY

Your use of HOPE is also governed by our Privacy Policy. Please review it carefully.

7. INTELLECTUAL PROPERTY

HOPE and its original content are protected by copyright and trademark laws. You may not copy, modify, or distribute our content without permission.

8. LIMITATION OF LIABILITY

TO THE MAXIMUM EXTENT PERMITTED BY LAW:

• HOPE is provided "as is" without warranties
• We are not liable for any indirect, incidental, or consequential damages
• Our total liability is limited to the amount you paid for the service (if any)

9. CRISIS SITUATIONS

If you or someone you know is in immediate danger:
• Call emergency services (911 in US, 112 in EU, 999 in UK)
• Go to the nearest emergency room
• Contact a crisis hotline (listed in Resources section)

10. TERMINATION

We reserve the right to terminate or suspend your access to HOPE at any time, without notice, for conduct that we believe violates these Terms.

11. CHANGES TO TERMS

We may modify these Terms at any time. Continued use of HOPE after changes constitutes acceptance of the new Terms.

12. GOVERNING LAW

These Terms are governed by the laws of the European Union.

13. CONTACT

For questions about these Terms: legal@hope-app.com

---

By using HOPE, you acknowledge that you have read, understood, and agree to these Terms of Service.
''',
  );
  
  /// Get privacy policy in specified language
  static LegalDocument getPrivacyPolicy(String languageCode) {
    // TODO: Add translations for other languages
    // For now, return English version
    return privacyPolicy;
  }
  
  /// Get terms of service in specified language
  static LegalDocument getTermsOfService(String languageCode) {
    // TODO: Add translations for other languages
    // For now, return English version
    return termsOfService;
  }
}
